---
- name: Update OS
  include_tasks: update_os.yml

- name: Install docker on Debian OS Family
  block:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - gnupg2

    - name: Add Docker GPG key
      apt_key:
        url: "{{ docker_apt_gpgkey }}"

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"

    - name: Install Docker
      apt:
        name: "{{ docker_package_name }}"
  when: ansible_os_family == "Debian"

- name: Install docker on Redhat OS Family
  block:
    - name: Add Docker repo
      get_url:
        url: "{{ docker_yum_repo_url }}"
        dest: "{{ docker_yum_repo_path }}"

    - name: install containerd
      command: yum install -y "{{ containerd_package }}"
      changed_when: false

    - name: Install Docker
      yum:
        name: "{{ docker_package_name }}"
        state: latest
      with_items:
        - "{{ docker_package_name }}"
        - "{{ docker_package_name }}-cli"
  when: ansible_os_family == "RedHat"

#---------FEDORA--------------------
- name: Install dependencies for Fedora
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - dnf
    - dnf-plugins-core
  when: ansible_distribution == "Fedora"


#---------DOCKER-COMPOSE---------------
- name: Install docker compose with pip
  block:
    - name: Install python3
      package:
        name: '{{ item }}'
        state: latest
      with_items:
        - python3
        - python3-pip

    - name: Install python3 dependencies for ubuntu
      package:
        name: '{{ item }}'
        state: latest
      when: ansible_distribution == 'Ubuntu'
      with_items:
        - python3-dev
        - build-essential
        - libssl-dev
        - libffi-dev
        - zlib1g-dev
        - libxml2-dev
        - libxslt1-dev

    - name: Upgrade pip3
      command: pip3 install --upgrade pip
      changed_when: false

    - name: Install docker compose
      pip:
        name: docker-compose=={{ docker_compose_version }}
        executable: pip3
  when: install_docker_compose == true
