---
- name: Update OS
  include_tasks: update_os.yml

- name: Install docker on Debian OS Family
  block:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gpg-agent

    - name: Add Docker GPG key
      apt_key:
        url: "{{ docker_apt_gpgkey }}"

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"

    - name: Install Docker
      apt:
        name: "{{ docker_package_name }}"
  when: ansible_os_family == "Debian"

- name: Install docker on Redhat OS Family
  block:
    - name: Add Docker repo
      get_url:
        url: "{{ docker_yum_repo_url }}"
        dest: "{{ docker_yum_repo_path }}"

    - name: Install dependencies for Fedora
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - dnf
        - dnf-plugins-core
      when: ansible_distribution == "Fedora"

    - name: Install Docker
      package:
        name: "{{ docker_package_name }}"
        state: latest
      with_items:
        - containerd.io
        - "{{ docker_package_name }}"
        - "{{ docker_package_name }}-cli"
  when: ansible_os_family == "RedHat"

- name: Install docker compose with pip
  block:
    - name: Install python3 and python3-pip
      package:
        name: '{{ item }}'
        state: latest
      with_items:
        - python3
        - python3-pip

    - name: Install docker compose with pip
      command: pip3 install docker-compose=={{ docker_compose_version }}
  when: install_docker_compose == true
